---
service:
  type: LoadBalancer
  spec:
    loadBalancerIP: "${SECRET_AUTHENTIK_ADDR}"
authentik:
  secret_key: "${SECRET_AUTHENTIK_KEY}"
  postgresql:
    user: authentik
    password: ${SECRET_POSTGRES_PASS}
    port: 5432

postgresql:
  enabled: true
  postgresqlPassword: ${SECRET_POSTGRES_PASS}
  persistence:
    enabled: true
    storageClass: storage-iscsi-synology-synology-csi-retain
    accessModes:
      - ReadWriteOnce

redis:
  enabled: true

ingress:
  enabled: true
  ingressClassName: "ingress-traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: auth.${SECRET_DOMAIN}
      paths:
        - path: "/"
          pathType: Prefix
  tls:
  - hosts:
    - auth.${SECRET_DOMAIN}
    secretName: authentik-tls-staging
