---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-nfs-subdir
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/storage-nfs-subdir/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-nfs-subdir-classes
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-storage-nfs-subdir
  path: ./kubernetes/apps/storage/storage-nfs-subdir/storageClasses
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
