---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: nfs-subdir-external-provisioner
  name: nfs-delete
parameters:
  archiveOnDelete: "false"
  pathPattern: ${.PVC.namespace}/${.PVC.name}
provisioner: cluster.local/storage-nfs-subdir-nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    app: nfs-subdir-external-provisioner
  name: nfs-retain
parameters:
  archiveOnDelete: "true"
  pathPattern: ${.PVC.namespace}/${.PVC.name}
provisioner: cluster.local/storage-nfs-subdir-nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
