---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-retain-claim
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-delete-claim
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
