---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1a2vwx4rvjxcl24lmd8dtn9mquge4jlp404nwmvacyq6kxre0jcvqd8l0q5
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1a2vwx4rvjxcl24lmd8dtn9mquge4jlp404nwmvacyq6kxre0jcvqd8l0q5
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1a2vwx4rvjxcl24lmd8dtn9mquge4jlp404nwmvacyq6kxre0jcvqd8l0q5
