---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./hajimari.yaml
  - ./ingress-traefik.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./storage-nfs-subdir.yaml
  - ./storage-iscsi-synology.yaml
