---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: storage-iscsi-synology
  namespace: flux-system
spec:
  interval: 1h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
