apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OXrnKIqLuANohzRWcHZyIf2lLZVHY9DH5sv1d+4kI6N0JtfmDclPWw==,iv:5OUwdp+dTX8+Fukvd7gncsHUtrc50Q68OQWzbm8BAgg=,tag:AZ+O8kp9e/p3Y+kSg9G6eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2vwx4rvjxcl24lmd8dtn9mquge4jlp404nwmvacyq6kxre0jcvqd8l0q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWmlzZGpzUG9Zc2dWV1pE
            Tm5nQklERVZqRFRjZHNadml3Q2VaZzgxREJvCnhlQ2JXdmtiTW9UL0NtU2EwZXBZ
            OTkyeTdPTFFlWHEzSVh5SGJQcjcyVFUKLS0tIEVrUFpaRUFDaGFZN2hONzVqM3M4
            REJGQ1FXcVUwenRsTEVZbHVkY2lXZ3MKcMwBhRCjcJ8anMp45Wyc0ly+t50um6Wr
            lmcde09ppHXkUlIhlzCsHuFOYe8Esis6hDnj8l/f6FOp2/vDU/C8/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-05T11:55:53Z"
    mac: ENC[AES256_GCM,data:ymJVPmec/bMDEi0bQgs6v7Vb0iEmcFHo1DhqLQmrbQaiIWjY4QWb1pFyujb3XaIY745877azUvZs2GzsWOd0taPyex9LMkHIiSUyagrrOmsLX3+dMOmS0q5L9qlVLf7rcTOHIZQVoS5JoecCnMCy37YEa+5xq2JHSktq2qupX9Y=,iv:MEd7vdtOftjdLs9RtGUsuNZCGrACtXsBp1UDjCngANg=,tag:kb9FqfsxZy8dJ7aRW7IfDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
