---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-iscsi-synology-config
  namespace: storage
spec:
  path: ./kubernetes/apps/storage/storage-iscsi-synology/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-iscsi-synology
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-storage-iscsi-synology-config
  path: ./kubernetes/apps/storage/storage-iscsi-synology/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: storage-iscsi-synology
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
