---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "authentik-tls-staging"
  namespace: networking
spec:
  secretName: "authentik-tls-staging"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "auth.${SECRET_DOMAIN}"
