apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:epofCW/84QdG3dSq7q6StI3R,iv:/xu2d0erN+8cwEAcFU4mDM7evMyWlpIRFNFMTTjST+s=,tag:w+DkU1KDhtlBE21FNtzbKQ==,type:str]
    api-key: ENC[AES256_GCM,data:UM8Y1VeGKzMsNHBDcNLkCe1tOiwYwqhce/lqvZI2EW0cG6Hirg==,iv:PvDi3Sd92kdidYSMe02ivr7PjPj7utPSisvry8VoMzs=,tag:q2WN82OiFQxlKPERIZu0Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2vwx4rvjxcl24lmd8dtn9mquge4jlp404nwmvacyq6kxre0jcvqd8l0q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcWVJY2RKczdyZzF3UElh
            c2FBSUFtYXpEdjBmZlpCMjBLN3dpUXVZYUFrCmRZY0pxRW40aXZUa21vNWJDdkM0
            dGlpTFc5M05sbXk1TU9zdmZSeXo5Sm8KLS0tIGR2RTZOQnZTcHl5dVZodkFzaG03
            UVlFeU44dHd2OXFkRlVnNC9HQ1hIOUUKVtyOg46V7FFsaaCjyTH+1OPqeKJLprMr
            5Pmhh8TdA6GqzQvawC46/2/0Mle9FRV44UcQJGQVwHGSb4kguap60A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T04:24:02Z"
    mac: ENC[AES256_GCM,data:n/j24iZrseGkjIQSBBN++kl5/vGplNB0JVwargq4D84X45cXwyaXV9PjiXZIhXuXHHhorUVffMBskLBDe6OaT2qt1K4GVi7jqP/nNmoIJDDafAPlT9r0foPzScE+0yDOxdyCYGL4Wk/q99b+NV4J+mLhUjCAc8mtp8iDg4LfLqo=,iv:HjXxwXOq/ajYcvJxyD7fMjmrJvoovWI0CYwE5XEQUlE=,tag:mPWEr+5ezhfZInXhNKklrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
