---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: networking
spec:
  interval: 5m
  releaseName: ingress-traefik
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-traefik
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
