---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ingress-traefik-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/networking/ingress-traefik/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-traefik-certificates
    - name: cluster-apps-metallb-config
  path: ./kubernetes/apps/networking/ingress-traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-traefik
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
