---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "10.0.1.100"
  METALLB_LB_RANGE: "10.0.1.101-10.0.1.250"
  METALLB_K8S_GATEWAY_ADDR: "10.0.1.101"
  METALLB_INGRESS_ADDR: "10.0.1.102"
